/**
 * Natural Satellite (Moon) Database
 * Real data sourced from NASA JPL Solar System Dynamics.
 */

import type { PlanetId } from "@/stores/solar-system-store";

export interface MoonInfo {
  id: string;
  name: string;
  planet: PlanetId;
  radius: number;           // km
  mass: number;             // × 10^20 kg
  gravity: number;          // m/s²
  orbitalPeriod: number;    // Earth days
  distanceFromPlanet: number; // km (semi-major axis)
  discoveryYear: number | null;
  discoveredBy: string;
  eccentricity: number;
  inclination: number;      // degrees
  fact: string;
  imageUrl: string;         // NASA image
}

// ─── Moon Database ───────────────────────────────────────────────────────────

export const MOONS_DATABASE: MoonInfo[] = [
  // ─── Earth ─────────────────────────────────────────────────────────────────
  {
    id: "moon",
    name: "Moon",
    planet: "earth",
    radius: 1737.4,
    mass: 734.9,
    gravity: 1.62,
    orbitalPeriod: 27.32,
    distanceFromPlanet: 384400,
    discoveryYear: null,
    discoveredBy: "Known since antiquity",
    eccentricity: 0.0549,
    inclination: 5.145,
    fact: "The Moon is the fifth largest satellite in the Solar System and the only celestial body beyond Earth visited by humans.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA12235/PIA12235~thumb.jpg",
  },

  // ─── Mars ──────────────────────────────────────────────────────────────────
  {
    id: "phobos",
    name: "Phobos",
    planet: "mars",
    radius: 11.27,
    mass: 0.000106,
    gravity: 0.0057,
    orbitalPeriod: 0.319,
    distanceFromPlanet: 9376,
    discoveryYear: 1877,
    discoveredBy: "Asaph Hall",
    eccentricity: 0.0151,
    inclination: 1.093,
    fact: "Phobos orbits so close to Mars that it completes an orbit faster than Mars rotates, rising in the west and setting in the east.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA10368/PIA10368~thumb.jpg",
  },
  {
    id: "deimos",
    name: "Deimos",
    planet: "mars",
    radius: 6.2,
    mass: 0.0000147,
    gravity: 0.003,
    orbitalPeriod: 1.263,
    distanceFromPlanet: 23463,
    discoveryYear: 1877,
    discoveredBy: "Asaph Hall",
    eccentricity: 0.00033,
    inclination: 0.93,
    fact: "Deimos is the smaller of Mars's two moons and is slowly spiraling away from the planet.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA11826/PIA11826~thumb.jpg",
  },

  // ─── Jupiter ───────────────────────────────────────────────────────────────
  {
    id: "io",
    name: "Io",
    planet: "jupiter",
    radius: 1821.6,
    mass: 893.2,
    gravity: 1.796,
    orbitalPeriod: 1.769,
    distanceFromPlanet: 421700,
    discoveryYear: 1610,
    discoveredBy: "Galileo Galilei",
    eccentricity: 0.0041,
    inclination: 0.05,
    fact: "Io is the most volcanically active body in the Solar System, with over 400 active volcanoes.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA01667/PIA01667~thumb.jpg",
  },
  {
    id: "europa",
    name: "Europa",
    planet: "jupiter",
    radius: 1560.8,
    mass: 480.0,
    gravity: 1.314,
    orbitalPeriod: 3.551,
    distanceFromPlanet: 671034,
    discoveryYear: 1610,
    discoveredBy: "Galileo Galilei",
    eccentricity: 0.009,
    inclination: 0.47,
    fact: "Europa has a subsurface ocean beneath its icy crust that may contain more water than all of Earth's oceans combined.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA19048/PIA19048~thumb.jpg",
  },
  {
    id: "ganymede",
    name: "Ganymede",
    planet: "jupiter",
    radius: 2634.1,
    mass: 1481.9,
    gravity: 1.428,
    orbitalPeriod: 7.155,
    distanceFromPlanet: 1070412,
    discoveryYear: 1610,
    discoveredBy: "Galileo Galilei",
    eccentricity: 0.0013,
    inclination: 0.2,
    fact: "Ganymede is the largest moon in the Solar System — larger than Mercury — and the only moon with its own magnetic field.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA01666/PIA01666~thumb.jpg",
  },
  {
    id: "callisto",
    name: "Callisto",
    planet: "jupiter",
    radius: 2410.3,
    mass: 1075.9,
    gravity: 1.235,
    orbitalPeriod: 16.689,
    distanceFromPlanet: 1882709,
    discoveryYear: 1610,
    discoveredBy: "Galileo Galilei",
    eccentricity: 0.0074,
    inclination: 0.192,
    fact: "Callisto has the oldest and most heavily cratered surface in the Solar System, with no evidence of tectonic activity.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA03456/PIA03456~thumb.jpg",
  },
  {
    id: "amalthea",
    name: "Amalthea",
    planet: "jupiter",
    radius: 83.5,
    mass: 0.0208,
    gravity: 0.02,
    orbitalPeriod: 0.498,
    distanceFromPlanet: 181366,
    discoveryYear: 1892,
    discoveredBy: "Edward Emerson Barnard",
    eccentricity: 0.003,
    inclination: 0.38,
    fact: "Amalthea is the reddest object in the Solar System and radiates more heat than it receives from sunlight.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA02532/PIA02532~thumb.jpg",
  },
  {
    id: "himalia",
    name: "Himalia",
    planet: "jupiter",
    radius: 85,
    mass: 0.067,
    gravity: 0.062,
    orbitalPeriod: 250.56,
    distanceFromPlanet: 11461000,
    discoveryYear: 1904,
    discoveredBy: "Charles Dillon Perrine",
    eccentricity: 0.162,
    inclination: 27.5,
    fact: "Himalia is the largest irregular satellite of Jupiter, likely a captured asteroid.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA02532/PIA02532~thumb.jpg",
  },

  // ─── Saturn ────────────────────────────────────────────────────────────────
  {
    id: "titan",
    name: "Titan",
    planet: "saturn",
    radius: 2574.7,
    mass: 1345.5,
    gravity: 1.352,
    orbitalPeriod: 15.945,
    distanceFromPlanet: 1221870,
    discoveryYear: 1655,
    discoveredBy: "Christiaan Huygens",
    eccentricity: 0.0288,
    inclination: 0.34,
    fact: "Titan is the only moon with a dense atmosphere and the only body besides Earth with stable surface liquids (methane lakes).",
    imageUrl: "https://images-assets.nasa.gov/image/PIA14602/PIA14602~thumb.jpg",
  },
  {
    id: "enceladus",
    name: "Enceladus",
    planet: "saturn",
    radius: 252.1,
    mass: 1.08,
    gravity: 0.113,
    orbitalPeriod: 1.37,
    distanceFromPlanet: 237948,
    discoveryYear: 1789,
    discoveredBy: "William Herschel",
    eccentricity: 0.0047,
    inclination: 0.019,
    fact: "Enceladus has geysers that shoot water ice into space, feeding Saturn's E ring and suggesting a subsurface ocean.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA17202/PIA17202~thumb.jpg",
  },
  {
    id: "rhea",
    name: "Rhea",
    planet: "saturn",
    radius: 763.8,
    mass: 23.07,
    gravity: 0.264,
    orbitalPeriod: 4.518,
    distanceFromPlanet: 527108,
    discoveryYear: 1672,
    discoveredBy: "Giovanni Cassini",
    eccentricity: 0.0013,
    inclination: 0.345,
    fact: "Rhea may have a faint ring system of its own, which would make it the only moon known to have rings.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA07763/PIA07763~thumb.jpg",
  },
  {
    id: "dione",
    name: "Dione",
    planet: "saturn",
    radius: 561.4,
    mass: 11.0,
    gravity: 0.232,
    orbitalPeriod: 2.737,
    distanceFromPlanet: 377396,
    discoveryYear: 1684,
    discoveredBy: "Giovanni Cassini",
    eccentricity: 0.0022,
    inclination: 0.019,
    fact: "Dione has bright ice cliffs called 'wispy terrain' and may have a subsurface ocean.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA07746/PIA07746~thumb.jpg",
  },
  {
    id: "tethys",
    name: "Tethys",
    planet: "saturn",
    radius: 531.1,
    mass: 6.18,
    gravity: 0.146,
    orbitalPeriod: 1.888,
    distanceFromPlanet: 294619,
    discoveryYear: 1684,
    discoveredBy: "Giovanni Cassini",
    eccentricity: 0.0001,
    inclination: 1.12,
    fact: "Tethys has a giant impact crater (Odysseus) that is 2/5 the diameter of the moon itself.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA07738/PIA07738~thumb.jpg",
  },
  {
    id: "iapetus",
    name: "Iapetus",
    planet: "saturn",
    radius: 734.5,
    mass: 18.06,
    gravity: 0.223,
    orbitalPeriod: 79.32,
    distanceFromPlanet: 3560820,
    discoveryYear: 1671,
    discoveredBy: "Giovanni Cassini",
    eccentricity: 0.0286,
    inclination: 15.47,
    fact: "Iapetus has a dramatic two-tone coloration — one hemisphere is bright white, the other dark as coal.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA08384/PIA08384~thumb.jpg",
  },
  {
    id: "mimas",
    name: "Mimas",
    planet: "saturn",
    radius: 198.2,
    mass: 0.375,
    gravity: 0.064,
    orbitalPeriod: 0.942,
    distanceFromPlanet: 185539,
    discoveryYear: 1789,
    discoveredBy: "William Herschel",
    eccentricity: 0.0196,
    inclination: 1.574,
    fact: "Mimas has the giant Herschel crater making it resemble the Death Star from Star Wars.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA12570/PIA12570~thumb.jpg",
  },

  // ─── Uranus ────────────────────────────────────────────────────────────────
  {
    id: "titania",
    name: "Titania",
    planet: "uranus",
    radius: 788.4,
    mass: 35.27,
    gravity: 0.379,
    orbitalPeriod: 8.706,
    distanceFromPlanet: 435910,
    discoveryYear: 1787,
    discoveredBy: "William Herschel",
    eccentricity: 0.0011,
    inclination: 0.34,
    fact: "Titania is the largest moon of Uranus and may have a subsurface ocean.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00039/PIA00039~thumb.jpg",
  },
  {
    id: "oberon",
    name: "Oberon",
    planet: "uranus",
    radius: 761.4,
    mass: 30.14,
    gravity: 0.347,
    orbitalPeriod: 13.463,
    distanceFromPlanet: 583520,
    discoveryYear: 1787,
    discoveredBy: "William Herschel",
    eccentricity: 0.0014,
    inclination: 0.058,
    fact: "Oberon's surface is covered in impact craters and has a mountain that is at least 6 km high.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00034/PIA00034~thumb.jpg",
  },
  {
    id: "ariel",
    name: "Ariel",
    planet: "uranus",
    radius: 578.9,
    mass: 13.53,
    gravity: 0.269,
    orbitalPeriod: 2.52,
    distanceFromPlanet: 191020,
    discoveryYear: 1851,
    discoveredBy: "William Lassell",
    eccentricity: 0.0012,
    inclination: 0.26,
    fact: "Ariel has the youngest and brightest surface of all Uranian moons, with extensive canyon systems.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00040/PIA00040~thumb.jpg",
  },
  {
    id: "miranda",
    name: "Miranda",
    planet: "uranus",
    radius: 235.8,
    mass: 0.66,
    gravity: 0.079,
    orbitalPeriod: 1.413,
    distanceFromPlanet: 129390,
    discoveryYear: 1948,
    discoveredBy: "Gerard Kuiper",
    eccentricity: 0.0013,
    inclination: 4.232,
    fact: "Miranda has the tallest cliff in the Solar System — Verona Rupes at 20 km high.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00044/PIA00044~thumb.jpg",
  },

  // ─── Neptune ───────────────────────────────────────────────────────────────
  {
    id: "triton",
    name: "Triton",
    planet: "neptune",
    radius: 1353.4,
    mass: 214.0,
    gravity: 0.779,
    orbitalPeriod: 5.877,
    distanceFromPlanet: 354759,
    discoveryYear: 1846,
    discoveredBy: "William Lassell",
    eccentricity: 0.000016,
    inclination: 156.885,
    fact: "Triton orbits Neptune in a retrograde direction, suggesting it was captured from the Kuiper Belt. It has active nitrogen geysers.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00317/PIA00317~thumb.jpg",
  },
  {
    id: "proteus",
    name: "Proteus",
    planet: "neptune",
    radius: 210,
    mass: 0.44,
    gravity: 0.07,
    orbitalPeriod: 1.122,
    distanceFromPlanet: 117647,
    discoveryYear: 1989,
    discoveredBy: "Voyager 2",
    eccentricity: 0.00053,
    inclination: 0.524,
    fact: "Proteus is the largest irregularly shaped moon — any larger and gravity would pull it into a sphere.",
    imageUrl: "https://images-assets.nasa.gov/image/PIA00054/PIA00054~thumb.jpg",
  },
];

/**
 * Get all moons for a given planet.
 */
export function getMoonsForPlanet(planetId: PlanetId): MoonInfo[] {
  return MOONS_DATABASE.filter((m) => m.planet === planetId);
}

/**
 * Get moon count per planet.
 */
export function getMoonCount(planetId: PlanetId): number {
  return MOONS_DATABASE.filter((m) => m.planet === planetId).length;
}
