/**
 * PDF Exporter — Mission Intelligence Report
 * 
 * Generates a professional A4 Landscape PDF with dark NASA theme,
 * white typography, purple accents, page numbers, and vector charts.
 * Production-quality aerospace document.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import type { MissionReportData } from "./types";

// ─── Color Constants ─────────────────────────────────────────────────────────

const C = {
  bg: "#ffffff",           // White background for PDF
  bgLight: "#f8f9fa",
  bgCard: "#f1f3f5",
  purple: "#6b21a8",       // Darker purple for visibility on white
  purpleLight: "#7c3aed",
  blue: "#1e40af",         // Darker blue
  blueLight: "#3b82f6",
  white: "#000000",        // Black text on white background
  gray: "#374151",         // Darker gray for readability
  grayDark: "#1f2937",     // Even darker
  green: "#059669",
  gold: "#d97706",
  red: "#dc2626",
  cyan: "#0891b2",
  border: "#e5e7eb",       // Light border
};

// ─── Styles ──────────────────────────────────────────────────────────────────

const styles: Record<string, any> = {
  pageTitle: { fontSize: 24, bold: true, color: C.white, margin: [0, 0, 0, 2] },
  title: { fontSize: 16, bold: true, color: C.white, margin: [0, 16, 0, 6] },
  subtitle: { fontSize: 11, color: C.gray, margin: [0, 0, 0, 12] },
  h2: { fontSize: 14, bold: true, color: C.white, margin: [0, 14, 0, 8] },
  h3: { fontSize: 11, bold: true, color: C.purpleLight, margin: [0, 10, 0, 4] },
  body: { fontSize: 9, color: C.gray },
  label: { fontSize: 7.5, color: C.grayDark },
  value: { fontSize: 9, color: C.white, bold: true },
  valueLarge: { fontSize: 18, color: C.white, bold: true },
  small: { fontSize: 7, color: C.grayDark },
  tableHeader: { fontSize: 7, bold: true, color: C.white },
  tableCell: { fontSize: 7, color: C.gray },
  cardLabel: { fontSize: 7.5, color: C.gray },
  cardValue: { fontSize: 14, bold: true, color: C.white },
  missionId: { fontSize: 8, color: C.purpleLight },
};

// ─── Main Export ─────────────────────────────────────────────────────────────

export async function exportToPDF(data: MissionReportData): Promise<void> {
  const pdfMake = (await import("pdfmake/build/pdfmake")).default;
  const pdfFonts = (await import("pdfmake/build/vfs_fonts")).default;
  const pm = pdfMake as any;
  const fonts = pdfFonts as any;
  pm.vfs = fonts.pdfMake ? fonts.pdfMake.vfs : fonts.vfs;

  const content: any[] = [];

  // Page 1: Title + Radar
  content.push(...buildTitlePage(data));
  // Page 2: Executive Summary
  content.push({ text: "", pageBreak: "before" });
  content.push(...buildExecutiveSummary(data));
  // Page 3: Mission Analysis
  content.push({ text: "", pageBreak: "before" });
  content.push(...buildMissionAnalysis(data));
  // Page 4+: Satellite Catalog
  content.push({ text: "", pageBreak: "before" });
  content.push(...buildSatelliteCatalog(data));
  // Charts & Distribution
  content.push({ text: "", pageBreak: "before" });
  content.push(...buildChartsPage(data));
  // Celestial: ISS, Moon, Sun, Planets
  content.push({ text: "", pageBreak: "before" });
  content.push(...buildCelestialPage(data));

  const doc: any = {
    pageSize: "A4",
    pageOrientation: "landscape",
    pageMargins: [40, 50, 40, 50],
    background: () => ({
      canvas: [{ type: "rect", x: 0, y: 0, w: 841.89, h: 595.28, color: C.bg }],
    }),
    header: (page: number) => ({
      columns: [
        { text: `MISSION: ${data.config.missionName}`, style: "small", color: C.grayDark, margin: [40, 20, 0, 0] },
        { text: `ID: ${data.config.missionId}`, style: "small", color: C.purpleLight, alignment: "center", margin: [0, 20, 0, 0] },
        { text: `PAGE ${page}`, style: "small", color: C.grayDark, alignment: "right", margin: [0, 20, 40, 0] },
      ],
    }),
    footer: () => ({
      columns: [
        { text: "Generated by Zenith · Data: NASA / CelesTrak / JPL Horizons / Astronomy Engine", style: "small", margin: [40, 0, 0, 0] },
        { text: data.generatedAt, style: "small", alignment: "right", margin: [0, 0, 40, 0] },
      ],
      margin: [0, 10, 0, 0],
    }),
    content,
    styles,
    defaultStyle: { font: "Roboto", color: C.gray, fontSize: 9 },
  };

  const pdf = pm.createPdf(doc);
  return new Promise<void>((resolve) => {
    pdf.getBlob((blob: Blob) => {
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${data.config.missionName.replace(/\s+/g, "_")}_${data.config.missionId}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setTimeout(() => URL.revokeObjectURL(url), 1000);
      resolve();
    });
  });
}

// ─── Page 1: Title + Radar ───────────────────────────────────────────────────

function buildTitlePage(data: MissionReportData): any[] {
  const { config } = data;
  const content: any[] = [];

  content.push({ text: "MISSION INTELLIGENCE REPORT", style: "pageTitle" });
  content.push({ text: config.missionName, style: "subtitle" });
  content.push({ text: `Mission ID: ${config.missionId}`, style: "missionId", margin: [0, 0, 0, 16] });

  // Two-column layout: Radar left, Info right
  const infoStack: any[] = [
    { text: "OBSERVER", style: "h3" },
    { text: config.observer.name || "Unknown", style: "value", margin: [0, 2, 0, 4] },
    { text: `${config.observer.latitude.toFixed(4)}°N, ${config.observer.longitude.toFixed(4)}°E`, fontSize: 8, color: C.gray, margin: [0, 0, 0, 8] },
    { text: "TIMEZONE", style: "label" },
    { text: config.observer.timezone, style: "value", margin: [0, 2, 0, 6] },
    { text: "UTC", style: "label" },
    { text: config.observer.currentUTC, style: "value", margin: [0, 2, 0, 6] },
    { text: "LOCAL TIME", style: "label" },
    { text: config.observer.currentLocal, style: "value", margin: [0, 2, 0, 6] },
    { text: "SEARCH RADIUS", style: "label" },
    { text: config.searchRadius > 0 ? `${config.searchRadius} km` : "No Limit", style: "value", margin: [0, 2, 0, 6] },
    { text: "VISIBLE OBJECTS", style: "label" },
    { text: `${data.statistics.visibleSatellites} satellites`, style: "value", margin: [0, 2, 0, 6] },
    { text: "TOTAL IN REPORT", style: "label" },
    { text: `${data.satellites.length} satellites`, style: "value", margin: [0, 2, 0, 6] },
    { text: "GENERATION", style: "label" },
    { text: new Date(data.generatedAt).toLocaleString(), style: "value", margin: [0, 2, 0, 0] },
  ];

  if (data.radarScreenshot) {
    content.push({
      columns: [
        { width: "65%", image: data.radarScreenshot, fit: [480, 380] },
        { width: "35%", stack: infoStack, margin: [16, 0, 0, 0] },
      ],
      columnGap: 10,
    });
  } else {
    content.push({ stack: infoStack });
  }

  return content;
}

// ─── Page 2: Executive Summary ───────────────────────────────────────────────

function buildExecutiveSummary(data: MissionReportData): any[] {
  const content: any[] = [];
  const s = data.statistics;

  content.push({ text: "EXECUTIVE SUMMARY", style: "pageTitle" });
  content.push({ text: "Key metrics from the current observation window", style: "subtitle" });

  // Dashboard cards (3 columns x 3 rows)
  const cards = [
    { label: "VISIBLE SATELLITES", value: s.visibleSatellites.toLocaleString(), color: C.green },
    { label: "COUNTRIES", value: s.countriesRepresented.toLocaleString(), color: C.blue },
    { label: "MISSION TYPES", value: s.categoriesCount.toLocaleString(), color: C.purpleLight },
    { label: "ORBIT TYPES", value: s.orbitTypesCount.toLocaleString(), color: C.cyan },
    { label: "AVG ALTITUDE", value: `${s.averageAltitude.toFixed(0)} km`, color: C.gold },
    { label: "AVG SPEED", value: `${s.averageSpeed.toFixed(2)} km/s`, color: C.blueLight },
    { label: "HIGHEST SAT", value: `${s.highestSatellite.altitude.toFixed(0)} km`, color: C.purpleLight },
    { label: "NEAREST SAT", value: `${s.nearestObject.distance.toFixed(0)} km`, color: C.green },
    { label: "TOTAL SCANNED", value: s.totalScanned.toLocaleString(), color: C.gray },
  ];

  // Build card grid (3x3)
  const rows: any[] = [];
  for (let i = 0; i < cards.length; i += 3) {
    const row = cards.slice(i, i + 3);
    rows.push({
      columns: row.map((card) => ({
        width: "33%",
        stack: [
          { canvas: [{ type: "rect", x: 0, y: 0, w: 230, h: 55, r: 4, color: C.bgCard }] },
          { text: card.label, style: "cardLabel", relativePosition: { x: 10, y: -48 } },
          { text: card.value, fontSize: 16, bold: true, color: card.color, relativePosition: { x: 10, y: -38 } },
        ],
        margin: [0, 0, 8, 8],
      })),
    });
  }
  content.push(...rows);

  // Key details table
  content.push({ text: "DETAILED METRICS", style: "h3", margin: [0, 12, 0, 6] });
  const detailRows = [
    ["Most Common Orbit", s.mostCommonOrbit],
    ["Highest Satellite", `${s.highestSatellite.name} (${s.highestSatellite.altitude.toFixed(0)} km)`],
    ["Lowest Satellite", `${s.lowestSatellite.name} (${s.lowestSatellite.altitude.toFixed(0)} km)`],
    ["Fastest Object", `${s.fastestObject.name} (${s.fastestObject.speed.toFixed(2)} km/s)`],
    ["Nearest Object", `${s.nearestObject.name} (${s.nearestObject.distance.toFixed(0)} km)`],
    ["Farthest Object", `${s.farthestObject.name} (${s.farthestObject.distance.toFixed(0)} km)`],
    ["Objects in Report", `${s.filteredObjects}`],
  ];

  content.push({
    table: {
      widths: ["35%", "65%"],
      body: detailRows.map(([label, value]) => [
        { text: label, style: "label", margin: [4, 3, 4, 3] },
        { text: value, style: "value", margin: [4, 3, 4, 3] },
      ]),
    },
    layout: { hLineWidth: () => 0.3, vLineWidth: () => 0, hLineColor: () => C.border },
  });

  return content;
}

// ─── Page 3: Mission Analysis ────────────────────────────────────────────────

function buildMissionAnalysis(data: MissionReportData): any[] {
  const content: any[] = [];

  content.push({ text: "MISSION ANALYSIS", style: "pageTitle" });
  content.push({ text: "Automated intelligence summary based on current observation data", style: "subtitle" });

  // Analysis paragraphs
  for (const line of data.missionAnalysis.summary) {
    content.push({
      text: line,
      fontSize: 10,
      color: C.white,
      margin: [0, 0, 0, 8],
      lineHeight: 1.4,
    });
  }

  // Quick stats sidebar
  content.push({ text: "", margin: [0, 16, 0, 0] });
  content.push({
    canvas: [{ type: "line", x1: 0, y1: 0, x2: 760, y2: 0, lineWidth: 0.5, lineColor: C.border }],
  });
  content.push({ text: "DATA CONFIDENCE", style: "h3", margin: [0, 12, 0, 6] });
  content.push({
    columns: [
      { width: "25%", stack: [{ text: "Sources", style: "label" }, { text: "5 verified", style: "value" }] },
      { width: "25%", stack: [{ text: "Data Age", style: "label" }, { text: "< 10 seconds", style: "value" }] },
      { width: "25%", stack: [{ text: "Propagation", style: "label" }, { text: "SGP4 (NORAD)", style: "value" }] },
      { width: "25%", stack: [{ text: "Confidence", style: "label" }, { text: "HIGH", style: "value", color: C.green }] },
    ],
  });

  return content;
}

// ─── Page 4: Satellite Catalog ───────────────────────────────────────────────

function buildSatelliteCatalog(data: MissionReportData): any[] {
  const content: any[] = [];

  content.push({ text: "SATELLITE CATALOG", style: "pageTitle" });
  content.push({ text: `${data.satellites.length} satellites matching current filter criteria`, style: "subtitle" });

  if (data.satellites.length === 0) {
    content.push({ text: "No satellites match the current filter criteria.", style: "body", color: C.gold });
    return content;
  }

  const headerRow = [
    "NORAD", "Name", "Country", "Category", "Orbit",
    "Alt (km)", "Speed", "Lat", "Lon", "Inc",
    "Year", "Visibility", "Dist (km)", "Status",
  ].map((h) => ({ text: h, style: "tableHeader", fillColor: C.bgCard, margin: [2, 3, 2, 3] }));

  const bodyRows = data.satellites.map((sat, i) => {
    const rowBg = i % 2 === 0 ? C.bgLight : null;
    const visBadge = sat.visibility === "Visible"
      ? { text: "● Visible", color: C.green, fontSize: 7 }
      : { text: "○ Below", color: C.grayDark, fontSize: 7 };
    return [
      { text: String(sat.noradId), style: "tableCell", fillColor: rowBg },
      { text: sat.name.length > 14 ? sat.name.slice(0, 14) + "…" : sat.name, style: "tableCell", fillColor: rowBg },
      { text: sat.country.length > 10 ? sat.country.slice(0, 10) + "…" : sat.country, style: "tableCell", fillColor: rowBg },
      { text: sat.category, style: "tableCell", fillColor: rowBg, color: C.purpleLight },
      { text: sat.orbitType, style: "tableCell", fillColor: rowBg, color: C.blueLight },
      { text: sat.altitude.toFixed(0), style: "tableCell", fillColor: rowBg },
      { text: `${sat.speedKms.toFixed(2)}`, style: "tableCell", fillColor: rowBg },
      { text: sat.latitude.toFixed(2), style: "tableCell", fillColor: rowBg },
      { text: sat.longitude.toFixed(2), style: "tableCell", fillColor: rowBg },
      { text: sat.inclination ? `${sat.inclination.toFixed(1)}°` : "—", style: "tableCell", fillColor: rowBg },
      { text: sat.launchYear ? String(sat.launchYear) : "—", style: "tableCell", fillColor: rowBg },
      { ...visBadge, fillColor: rowBg },
      { text: sat.distanceFromObserver.toFixed(0), style: "tableCell", fillColor: rowBg },
      { text: "● Active", style: "tableCell", fillColor: rowBg, color: C.green },
    ];
  });

  content.push({
    table: {
      headerRows: 1,
      widths: ["auto", "*", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto"],
      body: [headerRow, ...bodyRows],
    },
    layout: {
      hLineWidth: (i: number) => (i <= 1) ? 0.6 : 0.2,
      vLineWidth: () => 0,
      hLineColor: (i: number) => (i <= 1) ? C.purple : C.border,
      paddingLeft: () => 2,
      paddingRight: () => 2,
      paddingTop: () => 2,
      paddingBottom: () => 2,
    },
  });

  return content;
}

// ─── Page 5: Charts & Distribution ──────────────────────────────────────────

function buildChartsPage(data: MissionReportData): any[] {
  const content: any[] = [];

  content.push({ text: "DISTRIBUTION ANALYSIS", style: "pageTitle" });
  content.push({ text: "Statistical breakdown of satellite population", style: "subtitle" });

  // Category breakdown (pie-like visualization using bars)
  content.push({ text: "SATELLITE CATEGORIES", style: "h3" });
  if (data.categoryBreakdown.length > 0) {
    content.push(buildDistributionTable(
      data.categoryBreakdown.map((c) => ({ label: c.category.toUpperCase(), count: c.count, pct: c.percentage, color: c.color }))
    ));
  }

  // Orbit types
  content.push({ text: "ORBIT TYPES", style: "h3" });
  if (data.orbitTypeBreakdown.length > 0) {
    content.push(buildDistributionTable(
      data.orbitTypeBreakdown.map((o) => ({ label: o.type, count: o.count, pct: o.percentage, color: C.blueLight }))
    ));
  }

  // Altitude distribution
  content.push({ text: "ALTITUDE DISTRIBUTION", style: "h3" });
  if (data.altitudeDistribution.length > 0) {
    const maxCount = Math.max(...data.altitudeDistribution.map((a) => a.count), 1);
    content.push(buildDistributionTable(
      data.altitudeDistribution.map((a) => ({ label: a.range, count: a.count, pct: (a.count / maxCount) * 100, color: C.purpleLight }))
    ));
  }

  // Country distribution (top 10)
  content.push({ text: "COUNTRY DISTRIBUTION (TOP 10)", style: "h3" });
  if (data.countryBreakdown.length > 0) {
    content.push(buildDistributionTable(
      data.countryBreakdown.slice(0, 10).map((c) => ({ label: c.country, count: c.count, pct: c.percentage, color: C.gold }))
    ));
  }

  return content;
}

function buildDistributionTable(items: Array<{ label: string; count: number; pct: number; color: string }>): any {
  const body = items.map((item) => {
    // Use a canvas-drawn bar instead of Unicode block characters (which aren't supported in Roboto font)
    const barWidth = 200;
    const filledWidth = Math.round((item.pct / 100) * barWidth);

    return [
      { text: item.label, style: "tableCell", margin: [2, 4, 2, 4] },
      { text: String(item.count), style: "tableCell", alignment: "right", margin: [2, 4, 2, 4] },
      { text: `${item.pct.toFixed(1)}%`, style: "tableCell", alignment: "right", margin: [2, 4, 2, 4] },
      {
        canvas: [
          // Background track
          { type: "rect", x: 0, y: 3, w: barWidth, h: 8, r: 2, color: C.bgCard },
          // Filled portion
          ...(filledWidth > 0 ? [{ type: "rect", x: 0, y: 3, w: filledWidth, h: 8, r: 2, color: item.color }] : []),
        ],
        margin: [2, 2, 2, 2],
      } as any,
    ];
  });

  return {
    table: {
      widths: ["25%", "10%", "10%", "55%"],
      body,
    },
    layout: { hLineWidth: () => 0.2, vLineWidth: () => 0, hLineColor: () => C.border },
    margin: [0, 4, 0, 12],
  };
}

// ─── Page 6: Celestial Bodies ────────────────────────────────────────────────

function buildCelestialPage(data: MissionReportData): any[] {
  const content: any[] = [];

  content.push({ text: "CELESTIAL OBSERVATIONS", style: "pageTitle" });
  content.push({ text: "Sun, Moon, Planets, and ISS status at observation time", style: "subtitle" });

  const columns: any[] = [];

  // ISS Section
  if (data.issData) {
    const iss = data.issData;
    columns.push({
      width: "50%",
      stack: [
        { text: "ISS OPERATIONS", style: "h3" },
        buildLabelValue("Speed", `${iss.speed.toFixed(2)} km/s (${(iss.speed * 3600).toFixed(0)} km/h)`),
        buildLabelValue("Altitude", `${iss.altitude.toFixed(1)} km`),
        buildLabelValue("Latitude", `${iss.latitude.toFixed(4)}°`),
        buildLabelValue("Longitude", `${iss.longitude.toFixed(4)}°`),
        ...(iss.nextPass ? [buildLabelValue("Next Pass", iss.nextPass)] : []),
        ...(iss.maxElevation ? [buildLabelValue("Max Elevation", `${iss.maxElevation.toFixed(1)}°`)] : []),
        ...(iss.duration ? [buildLabelValue("Duration", `${iss.duration}s`)] : []),
        buildLabelValue("Status", "Operational"),
      ],
    });
  }

  // Sun Section
  if (data.sunData) {
    const sun = data.sunData;
    columns.push({
      width: "50%",
      stack: [
        { text: "SOLAR REPORT", style: "h3" },
        buildLabelValue("Elevation", `${sun.elevation.toFixed(1)}°`),
        buildLabelValue("Azimuth", `${sun.azimuth.toFixed(1)}°`),
        buildLabelValue("Visibility", sun.isVisible ? "Above Horizon" : "Below Horizon"),
        buildLabelValue("Sunrise", sun.sunrise || "—"),
        buildLabelValue("Sunset", sun.sunset || "—"),
        buildLabelValue("Solar Noon", sun.solarNoon || "—"),
        buildLabelValue("Golden Hour", sun.goldenHourStart || "—"),
        buildLabelValue("Civil Dawn", sun.civilDawn || "—"),
        buildLabelValue("Civil Dusk", sun.civilDusk || "—"),
        buildLabelValue("Nautical Dawn", sun.nauticalDawn || "—"),
        buildLabelValue("Astro. Dawn", sun.astronomicalDawn || "—"),
      ],
    });
  }

  if (columns.length > 0) {
    content.push({ columns, columnGap: 20, margin: [0, 0, 0, 16] });
  }

  // Moon Section
  if (data.moonData) {
    const moon = data.moonData;
    content.push({
      canvas: [{ type: "line", x1: 0, y1: 0, x2: 760, y2: 0, lineWidth: 0.5, lineColor: C.border }],
      margin: [0, 8, 0, 8],
    });
    content.push({ text: "LUNAR REPORT", style: "h3" });
    content.push({
      columns: [
        { width: "33%", stack: [
          buildLabelValue("Phase", moon.phase),
          buildLabelValue("Illumination", `${moon.illumination.toFixed(0)}%`),
          buildLabelValue("Age", `${moon.moonAge.toFixed(1)} days`),
          buildLabelValue("Distance", `${moon.distance.toFixed(4)} AU`),
        ]},
        { width: "33%", stack: [
          buildLabelValue("Azimuth", `${moon.azimuth.toFixed(1)}°`),
          buildLabelValue("Elevation", `${moon.elevation.toFixed(1)}°`),
          buildLabelValue("Visibility", moon.isVisible ? "Visible" : "Below Horizon"),
          buildLabelValue("Constellation", moon.constellation),
        ]},
        { width: "33%", stack: [
          buildLabelValue("Moonrise", moon.moonRise || "—"),
          buildLabelValue("Moonset", moon.moonSet || "—"),
        ]},
      ],
      columnGap: 12,
    });
  }

  // Planets Section
  if (data.planets.length > 0) {
    content.push({
      canvas: [{ type: "line", x1: 0, y1: 0, x2: 760, y2: 0, lineWidth: 0.5, lineColor: C.border }],
      margin: [0, 12, 0, 8],
    });
    content.push({ text: "VISIBLE PLANETS", style: "h3" });

    const pHeader = ["Planet", "Magnitude", "Azimuth", "Elevation", "Distance (AU)", "Constellation", "Rise", "Set"].map(
      (h) => ({ text: h, style: "tableHeader", fillColor: C.bgCard, margin: [3, 3, 3, 3] })
    );
    const pRows = data.planets.map((p) => [
      { text: p.name, style: "tableCell", bold: true, color: C.gold },
      { text: p.magnitude.toFixed(1), style: "tableCell" },
      { text: `${p.azimuth.toFixed(1)}°`, style: "tableCell" },
      { text: `${p.elevation.toFixed(1)}°`, style: "tableCell" },
      { text: p.distance.toFixed(4), style: "tableCell" },
      { text: p.constellation, style: "tableCell" },
      { text: p.riseTime || "—", style: "tableCell" },
      { text: p.setTime || "—", style: "tableCell" },
    ]);

    content.push({
      table: { headerRows: 1, widths: ["*", "auto", "auto", "auto", "auto", "*", "auto", "auto"], body: [pHeader, ...pRows] },
      layout: { hLineWidth: () => 0.2, vLineWidth: () => 0, hLineColor: () => C.border },
    });
  }

  return content;
}

function buildLabelValue(label: string, value: string): any {
  return {
    columns: [
      { width: "40%", text: label, style: "label", margin: [0, 1, 0, 1] },
      { width: "60%", text: value, style: "value", margin: [0, 1, 0, 1] },
    ],
    margin: [0, 1, 0, 1],
  };
}

// ─── (Authentication page removed) ───────────────────────────────────────────
